version: 2
services:
  app:
    image: 100544965750.dkr.ecr.ap-northeast-1.amazonaws.com/jimoshare-app-rails
    command: bash -c "bundle exec rails db:migrate && bundle exec rails assets:precompile && bundle exec puma -C config/puma.rb"
    environment: # 練習なので直書きスタイルだが、実際はdotenvなどを使った方が良いと思う。
      RAILS_ENV: production
      RAILS_MASTER_KEY: 7b1e2092d7de301aeeb6267d3a89765e
      DATABASE_NAME: jimoshare_app_production
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: jimoshare-app-db.cazw7at7vqud.ap-northeast-1.rds.amazonaws.com
      TZ: Japan
    working_dir: /jimoshare
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: jimoshare-app-production/app
        awslogs-stream-prefix: jimoshare-app-production
  nginx:
    image: 100544965750.dkr.ecr.ap-northeast-1.amazonaws.com/jimoshare-app-nginx
    ports:
      - 80:80
    links:
      - app
    volumes_from:
      - app
    working_dir: /jimoshare
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: jimoshare-app-production/nginx
        awslogs-stream-prefix: jimoshare-app-production
