version: 2
services:
  app:
    image: 100544965750.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app-rails:latest
    command: bash -c "bundle exec rails db:migrate && bundle exec rails assets:precompile && bundle exec puma -C config/puma.rb"
    environment: # 練習なので直書きスタイルだが、実際はdotenvなどを使った方が良いと思う。
      RAILS_ENV: production
      RAILS_MASTER_KEY: 7b1e2092d7de301aeeb6267d3a89765e
      DATABASE_NAME: sample_app_production
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: sample-db.cazw7at7vqud.ap-northeast-1.rds.amazonaws.com
      TZ: Japan
    working_dir: /sample-app
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: sample-app-production/app
        awslogs-stream-prefix: sample-app-production
  nginx:
    image: 100544965750.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app-nginx:latest
    ports:
      - 80:80
    links:
      - app
    volumes_from:
      - app
    working_dir: /sample-app
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: sample-app-production/nginx
        awslogs-stream-prefix: sample-app-production
